openapi: 3.0.0
info:
  title: Btbutton
  version: '1.0'
  description: ''
servers:
  - url: 'http://localhost:3000'
paths:
  /user:
    get:
      summary: Test
      tags: []
      responses: {}
components:
  schemas: {}
